/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ConversionEntry = IDL.Record({
  'outputFilename' : IDL.Text,
  'timestamp' : Time,
  'preset' : IDL.Text,
  'tiktokUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addConversion' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getConversionHistory' : IDL.Func([], [IDL.Vec(ConversionEntry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ConversionEntry = IDL.Record({
    'outputFilename' : IDL.Text,
    'timestamp' : Time,
    'preset' : IDL.Text,
    'tiktokUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addConversion' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getConversionHistory' : IDL.Func(
        [],
        [IDL.Vec(ConversionEntry)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };